export const mockCaseList = [
    {
        id: '0001',
        driverImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        name: 'Chong Theng Ng',
        type: 'Ride-Hailing',
        source: 'Walk In',
        effectDate: '24/3/2025',
        driverId: 'GEODR216600',
        contact: '90527878',
        email: 'chongthengng@gmail.com',
        tripId: '1102374284',
        violation: 'Aggressive Behavior',
        status: 'Resolved',
        action: 'BAN',
        duration: 'Permanent',
        remarks: `The driver has been permanently banned due to unacceptable and aggressive behavior. The individual showed up at the office premises and proceeded to act in a confrontational and disrespectful manner.
  
  During the incident, the driver raised their voice and began yelling at two staff members, Nalini and Jayden, causing a disruption in the workplace and creating a hostile environment.
  
  This behavior is a clear violation of our professional conduct policies and poses a safety concern for our employees.
  
  As a result, immediate disciplinary action was taken, and the driver’s account has been permanently banned.`,
        customerService: {
            userType: 'Driver',
            fleetType: 'Taxi (TDVL)',
            transactionId: '-',
            serviceType: '-',
            typeOfIssue: 'Behavioural',
            incidentDate: '21/3/2025',
            startTime: '10.35 am',
            endTime: '11.14 am',
            ticketDate: '21/3/2025',
            resolvedBy: 'Evelyn',
            resolvedDate: '24/3/2025',
        },
        compliance: {
            inputBy: 'Syaffiq',
            verdictBy: 'Auto',
            reinstatedBy: '-',
            handler: 'Nalini',
            suspensionStartDate: '24/3/2025',
            suspensionEndDate: '-',
        }
    },
    {
        id: '0002',
        name: 'Sarah Lim',
        contact: '91234567',
        driverImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        driverId: 'GEODR543210',
        tripId: '1102374285',
        type: 'Ride-Hailing',
        effectDate: '25/3/2025',
        action: 'SUSPENSION',
        status: 'Pending',
        email: 'sarahlim@gmail.com',
        violation: 'Late Pick-up (M)',
        remarks: `Driver failed to show up for scheduled pick-up on time multiple times. Complaints were filed by users and investigation is ongoing.`,
        customerService: {
            source: 'App Report',
            userType: 'Passenger',
            fleetType: 'Car (PDVL)',
            transactionId: 'TXN12345',
            serviceType: 'Booking',
            typeOfIssue: 'Punctuality',
            incidentDate: '23/3/2025',
            startTime: '8.00 am',
            endTime: '8.30 am',
            resolvedDate: '-',
        },
        compliance: {
            inputBy: 'Darren',
            verdictBy: 'Pending',
            reinstatedBy: '-',
            handler: 'Lily',
        }
    },
    {
        id: '0003',
        name: 'Mohammed Faisal',
        contact: '93334444',
        driverImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        driverId: 'GEODR998877',
        tripId: '1102374286',
        type: 'Ride-Hailing',
        effectDate: '20/3/2025',
        action: 'WARNING',
        status: 'Resolved',
        email: 'faisal.mohammed@gmail.com',
        violation: 'Unprofessional Attire (L)',
        remarks: `Driver was wearing inappropriate clothing that did not meet company standards. Given a formal warning.`,
        customerService: {
            source: 'Photo Review',
            userType: 'Rider',
            fleetType: 'Taxi (TDVL)',
            transactionId: '-',
            serviceType: '-',
            typeOfIssue: 'Appearance',
            incidentDate: '18/3/2025',
            startTime: '2.15 pm',
            endTime: '2.45 pm',
            resolvedDate: '20/3/2025',
        },
        compliance: {
            inputBy: 'Nalini',
            verdictBy: 'Manual',
            reinstatedBy: '-',
            handler: 'Zhang Wei',
        }
    },
];
